version: "3"
services:
  frontend:
    build: frontend/
    ports:
      - "30000:5173"
    volumes:
      - "./frontend:/app"
  
  server:
    build: server/
    ports:
      - "30001:30001"
    volumes:
      - "./server:/app"